default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    setup_ci
    build_app(
      scheme: "EmojiMaker",
      export_method: "app-store"
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci
    match(
      type: "appstore",
      readonly: true,
      git_url: ENV['MATCH_GIT_URL'],
      username: ENV['APPLE_ID']
    )

    build_app(
      scheme: "EmojiMaker",
      export_method: "app-store"
    )

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_KEY'],
      is_key_content_base64: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end