name: iOS CI - Build and TestFlight

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: macos-latest
    env:
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
      # Optional auth mechanisms for private match repo
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install gems
        run: bundle install --path vendor/bundle

      - name: Configure Git auth for match repo (HTTPS token)
        if: env.MATCH_GIT_TOKEN != ''
        run: |
          git config --global url."https://${{ env.MATCH_GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Setup SSH for match repo
        if: env.MATCH_GIT_PRIVATE_KEY != ''
        run: |
          mkdir -p ~/.ssh
          # Write key using heredoc to preserve exact newlines
          cat > ~/.ssh/match_key << 'EOF'
${{ env.MATCH_GIT_PRIVATE_KEY }}
EOF
          # Normalize Windows CRLF to LF to avoid format errors
          tr -d '\r' < ~/.ssh/match_key > ~/.ssh/match_key.unix
          mv ~/.ssh/match_key.unix ~/.ssh/match_key
          chmod 600 ~/.ssh/match_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          # Add key; if format error, try base64-decoding fallback
          ssh-add ~/.ssh/match_key || (base64 --decode ~/.ssh/match_key > ~/.ssh/match_key_decoded && chmod 600 ~/.ssh/match_key_decoded && ssh-add ~/.ssh/match_key_decoded)
          echo "SSH key added; using $MATCH_GIT_URL"

      - name: Build and Upload to TestFlight
        run: bundle exec fastlane beta